[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter2 = "EJeQnCNazSMJkKF2B91no1fms1VPHRDKM7tNs7quL3rT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xrei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
